global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3003']
  - job_name: 'encryption-service'
    static_configs:
      - targets: ['encryption-service:3002']
  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:3001']
