apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: medical-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: timmygunja/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: medical-system
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
