apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption-service
  namespace: medical-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encryption-service
  template:
    metadata:
      labels:
        app: encryption-service
    spec:
      containers:
        - name: encryption-service
          image: encryption-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: encryption-service
  namespace: medical-system
spec:
  selector:
    app: encryption-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
